[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.0.3",
    "openai>=1.54.3",
    "python-dotenv>=1.0.1",
]
